version: '3.8'

services:
  # Single PostgreSQL with all databases
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_dev
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for everything (cache, queues, sessions)
  redis:
    image: redis:8-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data

  # MinIO for file storage (if you really need it)
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data/minio:/data

  # Optional: MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
