name: 'Setup Node.js and pnpm'
description: 'Common setup steps for Node.js, pnpm, dependencies, and Prisma'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: 'latest'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: 'latest'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  generate-prisma:
    description: 'Whether to generate Prisma client'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Generate Prisma Client
      if: inputs.generate-prisma == 'true'
      run: pnpm db:generate
      shell: bash